import ContactSection from "@/components/sections/ContactSection";
import SubPageHeroSection from "@/components/sections/SubPageHeroSection";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <>
      <SubPageHeroSection
        image=""
        title="Kom igång"
        text="Är du redo för en förändring? Låt oss komma igång redan idag!"
        className="border-b bg-white"
      />
      <ContactSection />
    </>
  );
}
