import CenteredSection from "@/components/sections/CenteredSection";
import ContactSection from "@/components/sections/ContactSection";
import HeroSection from "@/components/sections/HeroSection";
import InfoCardSection from "@/components/sections/InfoCardSection";
import TwoPaneSection from "@/components/sections/TwoPaneSection";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <HeroSection />
      <CenteredSection
        image="/image003.jpeg"
        title="PERCEPTION ENABLED TECHNOLOGY"
        button={{
          href: "/",
          text: "Läs mer",
        }}
        text="Click here to edit this paragraph and add your own content. This is a
          great place to expand on the title and any relevant details or
          information."
      />
      <TwoPaneSection
        button={{
          href: "/",
          text: "Läs mer",
        }}
        image="/image002.jpeg"
        title="Title one"
        text="I'm a paragraph. Click here to add your own text and edit me. It’s easy. Just click “Edit Text” or double click me to add your own content and make changes to the font. I’m a great place for you to tell a story and let your users know a little more about you."
      />
      <InfoCardSection />
      <TwoPaneSection
        button={{
          href: "/",
          text: "Läs mer",
        }}
        rtl
        image="/image001.jpeg"
        title="Title two"
        text="I'm a paragraph. Click here to add your own text and edit me. It’s easy. Just click “Edit Text” or double click me to add your own content and make changes to the font. I’m a great place for you to tell a story and let your users know a little more about you."
      />
      <TwoPaneSection
        button={{
          href: "/",
          text: "Läs mer",
        }}
        className="bg-primary text-background"
        image="/image002.jpeg"
        title="Title one"
        text="I'm a paragraph. Click here to add your own text and edit me. It’s easy. Just click “Edit Text” or double click me to add your own content and make changes to the font. I’m a great place for you to tell a story and let your users know a little more about you."
      />
      <ContactSection />
    </>
  );
}
