import ContactSection from "@/components/sections/ContactSection";
import ServicesSection from "@/components/sections/ServicesSection";
import SubPageHeroSection from "@/components/sections/SubPageHeroSection";
import TrainersSection from "@/components/sections/TrainersSection";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <>
      <SubPageHeroSection
        image="/image006.webp"
        className="border-b bg-white"
        title="Två systrar med en passion för hälsa"
        text="Vi är två systrar som brinner för hälsa och träning. Vi har båda en bakgrund inom idrott och hälsa och har en passion för att hjälpa andra att uppnå sina mål."
      />
      <TrainersSection className="bg-white" />
      <ServicesSection className="bg-background" />
      <ContactSection className="bg-white" />
    </>
  );
}
